image: python:3.9

stages:
  - test

variables:
  FIREFOX_DRIVER_VERSION: "0.28.0"
  FIREFOX_DRIVER_URL: "https://github.com/mozilla/geckodriver/releases/download/v${FIREFOX_DRIVER_VERSION}/geckodriver-v${FIREFOX_DRIVER_VERSION}-linux64.tar.gz"

before_script:
  - apt-get update && apt-get install -y xvfb firefox
  - wget -O ~/FirefoxSetup.tar.bz2 "${FIREFOX_DRIVER_URL}"
  - tar xjf ~/FirefoxSetup.tar.bz2 -C /opt/
  - ln -s /opt/firefox/firefox /usr/lib/firefox
  - export PATH=$PATH:/opt/firefox/
  - pip install selenium pytest

test_firefox:
  stage: test
  script:
    - xvfb-run -a pytest tests/test_selenium.py
  artifacts:
    paths:
      - reports/
